/********************************************************************
* grlogdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error grlogdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevgrlogdict();
extern G__DLLEXPORT void G__set_cpp_environmentgrlogdict();
extern G__DLLEXPORT void G__cpp_setup_tagtablegrlogdict();
extern G__DLLEXPORT void G__cpp_setup_inheritancegrlogdict();
extern G__DLLEXPORT void G__cpp_setup_typetablegrlogdict();
extern G__DLLEXPORT void G__cpp_setup_memvargrlogdict();
extern G__DLLEXPORT void G__cpp_setup_globalgrlogdict();
extern G__DLLEXPORT void G__cpp_setup_memfuncgrlogdict();
extern G__DLLEXPORT void G__cpp_setup_funcgrlogdict();
extern G__DLLEXPORT void G__cpp_setupgrlogdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootgui.h"
#include "chipview.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__grlogdictLN_TClass;
extern G__linked_taginfo G__grlogdictLN_TBuffer;
extern G__linked_taginfo G__grlogdictLN_TMemberInspector;
extern G__linked_taginfo G__grlogdictLN_TObject;
extern G__linked_taginfo G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__grlogdictLN_TQObject;
extern G__linked_taginfo G__grlogdictLN_TGWindow;
extern G__linked_taginfo G__grlogdictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR;
extern G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__grlogdictLN_TH1F;
extern G__linked_taginfo G__grlogdictLN_TPad;
extern G__linked_taginfo G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__grlogdictLN_TGObject;
extern G__linked_taginfo G__grlogdictLN_TGFrame;
extern G__linked_taginfo G__grlogdictLN_TGCompositeFrame;
extern G__linked_taginfo G__grlogdictLN_TGMainFrame;
extern G__linked_taginfo G__grlogdictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__grlogdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__grlogdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__grlogdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__grlogdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__grlogdictLN_TH2I;
extern G__linked_taginfo G__grlogdictLN_CWaferDataBase;
extern G__linked_taginfo G__grlogdictLN_CChip;
extern G__linked_taginfo G__grlogdictLN_CWaferMap;
extern G__linked_taginfo G__grlogdictLN_CWmapInfo;
extern G__linked_taginfo G__grlogdictLN_GrLogMainFrame;
extern G__linked_taginfo G__grlogdictLN_CChipView;

/* STUB derived class for protected member access */
