//
// File generated by C:\root\\bin\rootcint at Mon Jun 01 12:00:43 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME grlogdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "grlogdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GrLogMainFrame_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_GrLogMainFrame(void *p);
   static void deleteArray_GrLogMainFrame(void *p);
   static void destruct_GrLogMainFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GrLogMainFrame*)
   {
      ::GrLogMainFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GrLogMainFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GrLogMainFrame", ::GrLogMainFrame::Class_Version(), "./rootgui.h", 40,
                  typeid(::GrLogMainFrame), DefineBehavior(ptr, ptr),
                  &::GrLogMainFrame::Dictionary, isa_proxy, 4,
                  sizeof(::GrLogMainFrame) );
      instance.SetDelete(&delete_GrLogMainFrame);
      instance.SetDeleteArray(&deleteArray_GrLogMainFrame);
      instance.SetDestructor(&destruct_GrLogMainFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GrLogMainFrame*)
   {
      return GenerateInitInstanceLocal((::GrLogMainFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GrLogMainFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void CChipView_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_CChipView(void *p);
   static void deleteArray_CChipView(void *p);
   static void destruct_CChipView(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CChipView*)
   {
      ::CChipView *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CChipView >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CChipView", ::CChipView::Class_Version(), "./chipview.h", 36,
                  typeid(::CChipView), DefineBehavior(ptr, ptr),
                  &::CChipView::Dictionary, isa_proxy, 4,
                  sizeof(::CChipView) );
      instance.SetDelete(&delete_CChipView);
      instance.SetDeleteArray(&deleteArray_CChipView);
      instance.SetDestructor(&destruct_CChipView);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CChipView*)
   {
      return GenerateInitInstanceLocal((::CChipView*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CChipView*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr GrLogMainFrame::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *GrLogMainFrame::Class_Name()
{
   return "GrLogMainFrame";
}

//______________________________________________________________________________
const char *GrLogMainFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GrLogMainFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GrLogMainFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GrLogMainFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GrLogMainFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GrLogMainFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GrLogMainFrame::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GrLogMainFrame*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr CChipView::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *CChipView::Class_Name()
{
   return "CChipView";
}

//______________________________________________________________________________
const char *CChipView::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CChipView*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CChipView::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CChipView*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CChipView::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CChipView*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CChipView::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CChipView*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void GrLogMainFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class GrLogMainFrame.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GrLogMainFrame::Class(),this);
   } else {
      R__b.WriteClassBuffer(GrLogMainFrame::Class(),this);
   }
}

//______________________________________________________________________________
void GrLogMainFrame::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GrLogMainFrame.
      typedef ::GrLogMainFrame msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMain", &fMain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas", &fEcanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWmapMode", &fWmapMode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWmap", (void*)&fWmap);
      R__insp.InspectMember("CWaferMap", (void*)&fWmap, "fWmap.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWmapInfo", (void*)&fWmapInfo);
      R__insp.InspectMember("CWmapInfo", (void*)&fWmapInfo, "fWmapInfo.", false);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_GrLogMainFrame(void *p) {
      delete ((::GrLogMainFrame*)p);
   }
   static void deleteArray_GrLogMainFrame(void *p) {
      delete [] ((::GrLogMainFrame*)p);
   }
   static void destruct_GrLogMainFrame(void *p) {
      typedef ::GrLogMainFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GrLogMainFrame

//______________________________________________________________________________
void CChipView::Streamer(TBuffer &R__b)
{
   // Stream an object of class CChipView.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(CChipView::Class(),this);
   } else {
      R__b.WriteClassBuffer(CChipView::Class(),this);
   }
}

//______________________________________________________________________________
void CChipView::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CChipView.
      typedef ::CChipView msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pixMap", &pixMap);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHist", &fHist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMain", &fMain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas", &fEcanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fViewMode", &fViewMode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChip", &fChip);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_CChipView(void *p) {
      delete ((::CChipView*)p);
   }
   static void deleteArray_CChipView(void *p) {
      delete [] ((::CChipView*)p);
   }
   static void destruct_CChipView(void *p) {
      typedef ::CChipView current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CChipView

/********************************************************
* grlogdict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablegrlogdict();

extern "C" void G__set_cpp_environmentgrlogdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("rootgui.h");
  G__add_compiledheader("chipview.h");
  G__cpp_reset_tagtablegrlogdict();
}
#include <new>
extern "C" int G__cpp_dllrevgrlogdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GrLogMainFrame */
static int G__grlogdict_519_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GrLogMainFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new GrLogMainFrame(
*(CWaferDataBase*) libp->para[0].ref, (TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) GrLogMainFrame(
*(CWaferDataBase*) libp->para[0].ref, (TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->CreateSubPads((TPad*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->Update();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GrLogMainFrame*) G__getstructoffset())->GetDB());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoSetMapMode();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((GrLogMainFrame*) G__getstructoffset())->SetMapMode((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((GrLogMainFrame*) G__getstructoffset())->SetMapMode();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GrLogMainFrame*) G__getstructoffset())->Add((CChip*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoOpenChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoFailList();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoClassList();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoReport();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoGeneratePickFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoGenerateJSONfile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoGenerateXMLfiles();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoPDReport();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoFullReport();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoStatistics();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->DoGenerateWaferMap();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->PrintWaferMap();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GrLogMainFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GrLogMainFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GrLogMainFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GrLogMainFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GrLogMainFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GrLogMainFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GrLogMainFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GrLogMainFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_519_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GrLogMainFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GrLogMainFrame G__TGrLogMainFrame;
static int G__grlogdict_519_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GrLogMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GrLogMainFrame*) (soff+(sizeof(GrLogMainFrame)*i)))->~G__TGrLogMainFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GrLogMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GrLogMainFrame*) (soff))->~G__TGrLogMainFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* CChipView */
static int G__grlogdict_520_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CChipView* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CChipView(
(CChip*) G__int(libp->para[0]), (TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) CChipView(
(CChip*) G__int(libp->para[0]), (TGWindow*) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__grlogdictLN_CChipView));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->CreateSubPads((TPad*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->SetTitle();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->Update();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoSetViewMode();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((CChipView*) G__getstructoffset())->SetViewMode((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((CChipView*) G__getstructoffset())->SetViewMode();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoGoPrevChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoGoNextChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoGoPrevDefectChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoGoNextDefectChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoGoPrevGoodChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->DoGoNextGoodChip();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->PrintChipView();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdatePixDef();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdateLevel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdateTrim((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdatePulse();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdatePh1();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdatePh2();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->UpdatePh21();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CChipView::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CChipView::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CChipView::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CChipView::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CChipView*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CChipView::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CChipView::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CChipView::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__grlogdict_520_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CChipView::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CChipView G__TCChipView;
static int G__grlogdict_520_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CChipView*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CChipView*) (soff+(sizeof(CChipView)*i)))->~G__TCChipView();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CChipView*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CChipView*) (soff))->~G__TCChipView();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GrLogMainFrame */

/* CChipView */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncgrlogdict {
 public:
  G__Sizep2memfuncgrlogdict(): p(&G__Sizep2memfuncgrlogdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncgrlogdict::*p)();
};

size_t G__get_sizep2memfuncgrlogdict()
{
  G__Sizep2memfuncgrlogdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancegrlogdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame))) {
     GrLogMainFrame *G__Lderived;
     G__Lderived=(GrLogMainFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame),G__get_linked_tagnum(&G__grlogdictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__grlogdictLN_CChipView))) {
     CChipView *G__Lderived;
     G__Lderived=(CChipView*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView),G__get_linked_tagnum(&G__grlogdictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablegrlogdict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__grlogdictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>::iterator_category,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>::value_type,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>::difference_type,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>::pointer,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>::reference>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,pair<unsigned int,int>,long>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,pair<unsigned int,int>,long,pair<unsigned int,int>*>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::const_iterator>::iterator_category,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::const_iterator>::value_type,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::const_iterator>::difference_type,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::const_iterator>::pointer,iterator_traits<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__grlogdictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__grlogdictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__grlogdictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__grlogdictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GrLogMainFrame */
static void G__setup_memvarGrLogMainFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame));
   { GrLogMainFrame *p; p=(GrLogMainFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TGMainFrame),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fWmapMode=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,1,0,G__get_linked_tagnum(&G__grlogdictLN_CWaferDataBase),-1,-1,4,"fDatabase=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__grlogdictLN_CWaferMap),-1,-1,4,"fWmap=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__grlogdictLN_CWmapInfo),-1,-1,4,"fWmapInfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* CChipView */
static void G__setup_memvarCChipView(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView));
   { CChipView *p; p=(CChipView*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TH2I),-1,-1,4,"pixMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TH1F),-1,-1,4,"fHist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TGMainFrame),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fViewMode=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_CChip),-1,-1,4,"fChip=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__grlogdictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvargrlogdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGrLogMainFrame(void) {
   /* GrLogMainFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame));
   G__memfunc_setup("AddButton",901,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'TGCompositeFrame' - 0 - frame C - - 0 - name "
"C - - 0 - caller", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateWmap",1016,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GrLogMainFrame",1355,G__grlogdict_519_0_3, 105, G__get_linked_tagnum(&G__grlogdictLN_GrLogMainFrame), -1, 0, 4, 1, 1, 0, 
"u 'CWaferDataBase' - 1 - waferData U 'TGWindow' - 10 - p "
"h - 'UInt_t' 0 - w h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateSubPads",1286,G__grlogdict_519_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TPad' - 0 - upad", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Update",611,G__grlogdict_519_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDB",422,G__grlogdict_519_0_6, 85, G__get_linked_tagnum(&G__grlogdictLN_CWaferDataBase), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSetMapMode",1154,G__grlogdict_519_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMapMode",975,G__grlogdict_519_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '-1' mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Add",265,G__grlogdict_519_0_9, 103, -1, -1, 0, 1, 1, 1, 0, "U 'CChip' - 0 - chip", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoOpenChip",969,G__grlogdict_519_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoFailList",971,G__grlogdict_519_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoClassList",1093,G__grlogdict_519_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoReport",815,G__grlogdict_519_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGeneratePickFile",1765,G__grlogdict_519_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGenerateJSONfile",1720,G__grlogdict_519_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGenerateXMLfiles",1762,G__grlogdict_519_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoPDReport",963,G__grlogdict_519_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoFullReport",1218,G__grlogdict_519_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoStatistics",1246,G__grlogdict_519_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGenerateWaferMap",1777,G__grlogdict_519_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintWaferMap",1312,G__grlogdict_519_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__grlogdict_519_0_22, 85, G__get_linked_tagnum(&G__grlogdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GrLogMainFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__grlogdict_519_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GrLogMainFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__grlogdict_519_0_24, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GrLogMainFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__grlogdict_519_0_25, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GrLogMainFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__grlogdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__grlogdict_519_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__grlogdict_519_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GrLogMainFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__grlogdict_519_0_31, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GrLogMainFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__grlogdict_519_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GrLogMainFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__grlogdict_519_0_33, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GrLogMainFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~GrLogMainFrame", 1481, G__grlogdict_519_0_34, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncCChipView(void) {
   /* CChipView */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__grlogdictLN_CChipView));
   G__memfunc_setup("AddButton",901,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'TGCompositeFrame' - 0 - frame C - - 0 - name "
"C - - 0 - caller", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateView",1022,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawInfoText",1215,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 4, 1, 4, 0, 
"i - - 0 - x i - - 0 - y "
"C - - 10 - name C - - 10 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawInfoFormat",1411,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 4, 8, 4, 0, 
"i - - 0 - x i - - 0 - y "
"C - - 10 - name C - - 10 - format", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawInfoDouble",1397,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 5, 1, 4, 0, 
"i - - 0 - x i - - 0 - y "
"C - - 10 - name d - - 0 - value "
"i - - 0 - prec", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawInfoInt",1093,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 4, 1, 4, 0, 
"i - - 0 - x i - - 0 - y "
"C - - 10 - name i - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawInfo",794,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CChipView",866,G__grlogdict_520_0_8, 105, G__get_linked_tagnum(&G__grlogdictLN_CChipView), -1, 0, 4, 1, 1, 0, 
"U 'CChip' - 0 - chip U 'TGWindow' - 10 - p "
"h - 'UInt_t' 0 - w h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateSubPads",1286,G__grlogdict_520_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TPad' - 0 - upad", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTitle",814,G__grlogdict_520_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Update",611,G__grlogdict_520_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSetViewMode",1279,G__grlogdict_520_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetViewMode",1100,G__grlogdict_520_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '-1' mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGoPrevChip",1162,G__grlogdict_520_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGoNextChip",1164,G__grlogdict_520_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGoPrevDefectChip",1749,G__grlogdict_520_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGoNextDefectChip",1751,G__grlogdict_520_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGoPrevGoodChip",1555,G__grlogdict_520_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoGoNextGoodChip",1557,G__grlogdict_520_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintChipView",1324,G__grlogdict_520_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdatePixDef",1187,G__grlogdict_520_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateLevel",1115,G__grlogdict_520_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTrim",1023,G__grlogdict_520_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - bit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdatePulse",1132,G__grlogdict_520_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdatePh1",844,G__grlogdict_520_0_25, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdatePh2",845,G__grlogdict_520_0_26, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdatePh21",894,G__grlogdict_520_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__grlogdict_520_0_28, 85, G__get_linked_tagnum(&G__grlogdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CChipView::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__grlogdict_520_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CChipView::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__grlogdict_520_0_30, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CChipView::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__grlogdict_520_0_31, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CChipView::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__grlogdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__grlogdict_520_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__grlogdict_520_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CChipView::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__grlogdict_520_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CChipView::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__grlogdict_520_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CChipView::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__grlogdict_520_0_39, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CChipView::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~CChipView", 992, G__grlogdict_520_0_40, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncgrlogdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalgrlogdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcgrlogdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__grlogdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR = { "iterator<random_access_iterator_tag,pair<unsigned int,int>,long,pair<unsigned int,int>*,pair<unsigned int,int>&>" , 115 , -1 };
G__linked_taginfo G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TPad = { "TPad" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__grlogdictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_TH2I = { "TH2I" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_CWaferDataBase = { "CWaferDataBase" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_CChip = { "CChip" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_CWaferMap = { "CWaferMap" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_CWmapInfo = { "CWmapInfo" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_GrLogMainFrame = { "GrLogMainFrame" , 99 , -1 };
G__linked_taginfo G__grlogdictLN_CChipView = { "CChipView" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablegrlogdict() {
  G__grlogdictLN_TClass.tagnum = -1 ;
  G__grlogdictLN_TBuffer.tagnum = -1 ;
  G__grlogdictLN_TMemberInspector.tagnum = -1 ;
  G__grlogdictLN_TObject.tagnum = -1 ;
  G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__grlogdictLN_TQObject.tagnum = -1 ;
  G__grlogdictLN_TGWindow.tagnum = -1 ;
  G__grlogdictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR.tagnum = -1 ;
  G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__grlogdictLN_TH1F.tagnum = -1 ;
  G__grlogdictLN_TPad.tagnum = -1 ;
  G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__grlogdictLN_TGObject.tagnum = -1 ;
  G__grlogdictLN_TGFrame.tagnum = -1 ;
  G__grlogdictLN_TGCompositeFrame.tagnum = -1 ;
  G__grlogdictLN_TGMainFrame.tagnum = -1 ;
  G__grlogdictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__grlogdictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__grlogdictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__grlogdictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__grlogdictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__grlogdictLN_TH2I.tagnum = -1 ;
  G__grlogdictLN_CWaferDataBase.tagnum = -1 ;
  G__grlogdictLN_CChip.tagnum = -1 ;
  G__grlogdictLN_CWaferMap.tagnum = -1 ;
  G__grlogdictLN_CWmapInfo.tagnum = -1 ;
  G__grlogdictLN_GrLogMainFrame.tagnum = -1 ;
  G__grlogdictLN_CChipView.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablegrlogdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TPad);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_TH2I);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_CWaferDataBase);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_CChip);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_CWaferMap);
   G__get_linked_tagnum_fwd(&G__grlogdictLN_CWmapInfo);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__grlogdictLN_GrLogMainFrame),sizeof(GrLogMainFrame),-1,324608,(char*)NULL,G__setup_memvarGrLogMainFrame,G__setup_memfuncGrLogMainFrame);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__grlogdictLN_CChipView),sizeof(CChipView),-1,324608,(char*)NULL,G__setup_memvarCChipView,G__setup_memfuncCChipView);
}
extern "C" void G__cpp_setupgrlogdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupgrlogdict()");
  G__set_cpp_environmentgrlogdict();
  G__cpp_setup_tagtablegrlogdict();

  G__cpp_setup_inheritancegrlogdict();

  G__cpp_setup_typetablegrlogdict();

  G__cpp_setup_memvargrlogdict();

  G__cpp_setup_memfuncgrlogdict();
  G__cpp_setup_globalgrlogdict();
  G__cpp_setup_funcgrlogdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncgrlogdict();
  return;
}
class G__cpp_setup_initgrlogdict {
  public:
    G__cpp_setup_initgrlogdict() { G__add_setup_func("grlogdict",(G__incsetup)(&G__cpp_setupgrlogdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initgrlogdict() { G__remove_setup_func("grlogdict"); }
};
G__cpp_setup_initgrlogdict G__cpp_setup_initializergrlogdict;

